(()=>{
 const byId=id=>document.getElementById(id),volume=byId('volume');
 function setVolume(){const value=Number(volume.value);byId('volumeValue').value=value;byId('volumeDial').style.transform=`rotate(${-135+value*2.7}deg)`;document.querySelectorAll('video').forEach(v=>v.volume=value/100)}
 volume.addEventListener('input',setVolume);setVolume();
 new MutationObserver(()=>document.querySelectorAll('video').forEach(v=>v.volume=Number(volume.value)/100)).observe(byId('directoryBody'),{childList:true});
 const sign=document.querySelector('.hanging-sign');function bump(){if(paused)return;sign.classList.remove('bump');void sign.offsetWidth;sign.classList.add('bump')}
 sign.addEventListener('pointerenter',bump);sign.addEventListener('click',bump);sign.addEventListener('animationend',()=>sign.classList.remove('bump'));
 const blimp=byId('showBlimp');let bx=innerWidth*.76,by=100,vx=-78,vy=49.5,blimpHover=false,previous=0,blimpAngle=0;
 blimp.addEventListener('pointerenter',()=>blimpHover=true);blimp.addEventListener('pointerleave',()=>blimpHover=false);blimp.addEventListener('focus',()=>blimpHover=true);blimp.addEventListener('blur',()=>blimpHover=false);
 blimp.onclick=()=>{openDirectory();byId('directoryTitle').textContent='Next stop: San Diego';byId('directoryBody').innerHTML='<h3>Hurtbox — No Love Lost</h3><p>October 2, 2026 · Spin Nightclub · San Diego<br>9 PM–4 AM · 21+ · With support from MUMBO</p><img class="show-poster" src="assets/hurtbox.webp" alt="Hurtbox show poster, October 2, 2026">'+link('https://instagram.com/mumbobeatz','Show updates','action-link')};
 const warpCanvas=byId('warpStars'),g=warpCanvas.getContext('2d');let flight=null;
 const rays=Array.from({length:240},()=>({angle:Math.random()*Math.PI*2,depth:Math.random(),width:Math.random()*1.8+.5,hue:180+Math.random()*95}));
 window.startWarp=(origin,reverse)=>{if(paused)return;const r=origin?.getBoundingClientRect();flight={start:performance.now(),x:r?r.left+r.width/2:innerWidth/2,y:r?r.top+r.height/2:innerHeight*.44,reverse};document.body.classList.add('in-warp');byId('speedReadout').textContent='WARP';warpCanvas.width=innerWidth;warpCanvas.height=innerHeight;};
 function drawWarp(now){if(!flight||!g)return;const progress=(now-flight.start)/1750;if(progress>=1){flight=null;g.clearRect(0,0,warpCanvas.width,warpCanvas.height);document.body.classList.remove('in-warp');byId('speedReadout').textContent='CRUISE';return}const ww=warpCanvas.width,hh=warpCanvas.height,blend=Math.min(1,progress*2),cx=flight.x+(ww/2-flight.x)*blend,cy=flight.y+(hh*.44-flight.y)*blend,reach=Math.hypot(ww,hh),spin=progress*(flight.reverse?-2.3:2.3);g.clearRect(0,0,ww,hh);const shade=g.createRadialGradient(cx,cy,8,cx,cy,reach*.65);shade.addColorStop(0,'#01020f');shade.addColorStop(.17,'#25134be6');shade.addColorStop(.52,'#103151c9');shade.addColorStop(1,'#030612cc');g.fillStyle=shade;g.fillRect(0,0,ww,hh);
 rays.forEach(ray=>{let z=(ray.depth+progress*1.8)%1;const radius=20+z*z*reach,angle=ray.angle+spin+(1-z)*1.35;const tail=Math.max(10,radius*(.06+progress*.2));g.beginPath();g.strokeStyle=`hsla(${ray.hue},95%,${70+z*25}%,${.2+z*.8})`;g.lineWidth=ray.width*(.4+z);g.moveTo(cx+Math.cos(angle-.03)*Math.max(0,radius-tail),cy+Math.sin(angle-.03)*Math.max(0,radius-tail));g.quadraticCurveTo(cx+Math.cos(angle)*radius,cy+Math.sin(angle)*radius,cx+Math.cos(angle+.025)*(radius+tail*.25),cy+Math.sin(angle+.025)*(radius+tail*.25));g.stroke()});
 }
 function frame(now){const dt=Math.min((now-previous)/1000,.05);previous=now;const maxX=Math.max(0,innerWidth-blimp.offsetWidth-8),maxY=Math.max(80,innerHeight-byId('cockpit').offsetHeight-blimp.offsetHeight-12);if(!paused&&current==='galaxy'){bx+=vx*dt;by+=vy*dt;if(bx<=8)vx=Math.abs(vx);if(bx>=maxX)vx=-Math.abs(vx);if(by<=75)vy=Math.abs(vy);if(by>=maxY)vy=-Math.abs(vy);blimp.dataset.direction=vx>0?'right':'left';}bx=Math.max(8,Math.min(maxX,bx));by=Math.max(75,Math.min(maxY,by));if(!paused)blimpAngle=Math.sin(now*.0012)*4;blimp.style.transform=`translate(${bx}px,${by}px) rotate(${blimpAngle}deg)`;if(flight){if(paused){flight=null;document.body.classList.remove('in-warp');byId('speedReadout').textContent='CRUISE'}else drawWarp(now)}requestAnimationFrame(frame)}
 if(!CITIES[current])closeStop();requestAnimationFrame(frame);
})();
