const SOCIALS=[['Instagram','@mumbobeatz','https://instagram.com/mumbobeatz'],['SoundCloud','Tracks, flips & mixes','https://soundcloud.com/mumbobeatz'],['YouTube','Sets & videos','https://www.youtube.com/@mumbobeatz'],['Spotify','Listen to MUMBO','https://open.spotify.com/artist/0v4RYCckfkFu4dXWl35BXl'],['Apple Music','Listen to MUMBO','https://music.apple.com/us/artist/mumbo/1811034573'],['TikTok','@mumbobeatz','https://www.tiktok.com/@mumbobeatz'],['Facebook','MUMBO','https://www.facebook.com/profile.php?id=61575874555012'],['X','@mumbobeatz','https://twitter.com/mumbobeatz']];
const link=(url,label,cls='')=>`<a class="${cls}" href="${url}" target="_blank" rel="noopener noreferrer">${label} ↗</a>`;
const platformLinks=`<div class="links">${SOCIALS.filter(x=>['SoundCloud','Spotify','Apple Music','YouTube'].includes(x[0])).map(x=>link(x[2],x[0])).join('')}</div>`;
const tracks=[['Feelin’ Pretty Suavé','Original'],['Missed Call','Original'],['Do It — MUMBO & Scum Wubz','Collaboration'],['Party Fix','Original'],['Satellite (Mumbo Flip)','Flip'],['Eat the Bass (Mumbo Flip)','Flip'],['Project Seismic','From the archive'],['As seen on…','EP'],['My Name Is I Like to Party 3','From the archive']];
const WORLDS={
music:{title:'Music Island',kicker:'01 / SOUND ON. WORLD OFF.',subtitle:'Dirty bass. Funky detours. A little bit of everything.',background:'studio',body:()=>`${platformLinks}<article class="featured"><video controls playsinline preload="metadata" poster="assets/studio.webp" aria-label="Feels Like Heaven visualizer"><source src="assets/heaven.mp4" type="video/mp4"></video><div><p class="eyebrow">ENTER THE CATHEDRAL</p><h2>Feels Like Heaven</h2><p>Step into the fog, follow the light, and turn it up.</p>${link('https://soundcloud.com/mumbobeatz','Listen on SoundCloud','action-link')}</div></article><h2 class="section-title">Releases & flips</h2><div class="track-grid">${tracks.map(([title,type])=>`<article class="track"><span class="type">${type}</span><h3>${title}</h3>${link('https://soundcloud.com/mumbobeatz','Browse on SoundCloud')}</article>`).join('')}</div><h2 class="section-title">Live sets & mixes</h2><div class="track-grid"><article class="track"><span class="type">Mix</span><h3>Mumbo’s Secret Stuff Vol. 1</h3>${link('https://soundcloud.com/mumbobeatz','Browse mixes')}</article><article class="track"><span class="type">Live set</span><h3>Emorfik 1/25: Mumbo Live Set!</h3>${link('https://www.youtube.com/@mumbobeatz','Visit YouTube channel')}</article><article class="track"><span class="type">Behind the Decks 03</span><h3>Zombae ft. Mumbo</h3>${link('https://www.youtube.com/@mumbobeatz','Visit YouTube channel')}</article></div><iframe class="embed" title="MUMBO on Spotify" loading="lazy" src="https://open.spotify.com/embed/artist/0v4RYCckfkFu4dXWl35BXl?utm_source=generator" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe>`},
events:{title:'Event Central',kicker:'02 / EVENTS ISLAND',subtitle:'From the rooftop to the festival grounds.',background:'hub',position:'5% 95%',body:()=>`<h2 class="section-title">Upcoming shows</h2><div class="event-row"><div><h3>Hurtbox — No Love Lost</h3><p>October 2, 2026 · Spin Nightclub · San Diego<br>9 PM–4 AM · 21+ · With support from MUMBO</p><img src="assets/hurtbox.webp" alt="Hurtbox show poster" style="width:min(280px,100%);border-radius:18px;margin-top:20px"></div>${link('https://instagram.com/mumbobeatz','Show updates','action-link')}</div><h2 class="section-title">From the archive</h2><div class="event-list"><article class="event-row"><div><small>FESTIVAL MEMORIES</small><h3>Dancefestopia</h3><p>Back in the world of bass.</p></div>${link('https://instagram.com/mumbobeatz','Photos & posts','action-link')}</article><article class="event-row"><div><small>ROOFTOP SESSIONS</small><h3>Nova</h3><p>House music, open skies, good company.</p></div>${link('https://www.instagram.com/p/Cfc1Padpnps/','See the post','action-link')}</article></div>`},
media:{title:'Media Center',kicker:'03 / TRANSMITTING FROM MUMBO’S WORLD',subtitle:'Clips, characters, memories, and wherever else you can find me.',background:'hub',position:'100% 0%',body:()=>`<div class="social-grid">${SOCIALS.map(([name,sub,url])=>`<a href="${url}" target="_blank" rel="noopener noreferrer"><strong>${name} ↗</strong><span>${sub}</span></a>`).join('')}</div><h2 class="section-title">A glimpse into the world</h2><div class="gallery"><figure><img src="assets/bass-bros.webp" alt="Super Bass Bros comic art featuring MUMBO and Balance" loading="lazy"><figcaption>Super Bass Bros · MUMBO × Balance</figcaption></figure><figure><img src="assets/live.webp" alt="MUMBO performing live" loading="lazy"><figcaption>Behind the decks</figcaption></figure><figure><img src="assets/sophie.webp" alt="Playful Sophie Cunningham cover artwork with a MUMBO SUCKS crowd sign" loading="lazy"><figcaption>A little mischief</figcaption></figure></div><div class="links">${link('https://mumbobeatz.com/highlights','More show memories')}<button class="action-link" data-go="about">Meet the man in the hat →</button></div>`},
about:{title:'Mumbo’s Moon',kicker:'THE LITTLE MOON / ABOUT MUMBO',subtitle:'Beep boop. Welcome to my corner of the universe.',background:'galaxy',body:()=>`<div class="about-layout"><img class="avatar" src="assets/character.webp" alt="MUMBO character in a fluffy blue jacket and star-covered bucket hat, carrying glowing headphones"><div class="about-copy"><p>I’m Ryan, aka MUMBO—a San Diego DJ and producer with a love for heavy bass, funky house, and taking the unexpected turn.</p><p>My sets move between sounds, but the goal stays the same: make you move your body and leave with a smile. That playful energy shows up in the music, the cartoons, the characters, and everything you’ll find here.</p><p>Mumbo’s World is where it all comes together. Pick a portal. Get a little lost.</p><div class="links">${link('https://instagram.com/mumbobeatz','Say hi on Instagram')}${link('mailto:mumbobeatz@gmail.com','Bookings')}</div></div></div>`},
toys:{title:'Mumbo’s Playground',kicker:'04 / PLAY IN PROGRESS',subtitle:'A new playground is taking shape.',background:'playground',body:()=>`<div class="toy-message"><p class="eyebrow">UNDER CONSTRUCTION</p><h2>Big kid energy. Work in progress.</h2><p>The rides, games, and strange little surprises are still being built. Come back for the grand opening.</p></div>`}
};
const WORLD_INFO={
 music:'Music and Live sets/mixes.',
 events:'Past and future Mumbo events.',
 media:'The social hub, connect to Mumbo in more ways than one!',
 about:'Meet Mumbo and explore the man behind the bucket hat.',
 toys:'All things Mumbo... merch, games, toys and much more.'
};
const MUSIC_ORDER=['as-seen-on','event-central','silly-singles','secret-stuff'];
const SUBWORLDS={
 'as-seen-on':{title:'As Seen On…',image:'as-seen-on-cutout-v3',info:'The debut EP: four songs and four corners of the park.',stops:[
  {name:'Power On',kind:'Track 1 · August 4, 2025',description:'Power On — MUMBO.',x:62,y:27,w:25,h:6,url:'https://open.spotify.com/artist/0v4RYCckfkFu4dXWl35BXl'},
  {name:'Mumbo Jumbo',kind:'Track 2 · August 4, 2025',description:'Mumbo Jumbo — MUMBO.',x:62,y:33,w:25,h:6,url:'https://open.spotify.com/artist/0v4RYCckfkFu4dXWl35BXl'},
  {name:'My Name Is (I Like to Party)',kind:'Track 3 · August 4, 2025',description:'My Name Is (I Like to Party) — MUMBO.',x:62,y:39,w:25,h:7,url:'https://open.spotify.com/artist/0v4RYCckfkFu4dXWl35BXl'},
  {name:'Berries & Cream',kind:'Track 4 · August 4, 2025',description:'Berries & Cream — MUMBO.',x:62,y:46,w:25,h:6,url:'https://open.spotify.com/artist/0v4RYCckfkFu4dXWl35BXl'},
  {name:'Mumbo Jumbo Park',kind:'Amusement park',description:'Roller coasters, rides and the Mumbo Jumbo side of the EP.',x:31,y:27,w:29,h:31},
  {name:'Hot Rod Arena',kind:'Skate / BMX / motocross park',description:'Ramps, dirt-bike jumps and tracks inspired by the Hot Rod world.',x:34,y:61,w:31,h:30},
  {name:'Berries & Cream Land',kind:'Playground and courts',description:'A berry-and-candy park with swings, basketball and tennis courts.',x:78,y:65,w:30,h:31}
 ]},
 'event-central':{title:'Event Central',image:'event-central-cutout-v3',info:'Upcoming and past shows.',stops:[
  {name:'Hurtbox — No Love Lost',kind:'Friday · October 2, 2026',description:'Spin Nightclub · San Diego, CA · 9 PM–4 AM · 21+. Hurtbox with Warlord, Proxxxy, Finnuh, 91Octane, Jonnyboy, Kurtzee, MUMBO and Sira.',x:75,y:27,w:29,h:43,url:'https://instagram.com/mumbobeatz',label:'Show updates'},
  {name:'Event Central Stage',kind:'Live show',description:'The next stop in Mumbo’s live universe.',x:52,y:48,w:30,h:42}
 ]},
 'silly-singles':{title:'Silly Singles',image:'music-cutout-v3',position:'left center',info:'The jukebox for singles, flips and one-off releases.',comingSoon:true,stops:[
  {name:'Silly Singles',kind:'Interactive jukebox · coming soon',description:'A future jukebox for MUMBO singles with Apple Music, Spotify, SoundCloud and YouTube links.',x:24,y:28,w:35,h:42,url:'https://soundcloud.com/mumbobeatz',label:'Browse SoundCloud'}
 ]},
 'secret-stuff':{title:'Mumbo’s Secret Stuff',image:'secret-stuff-cutout-v3',info:'SoundCloud-exclusive mashups from Mumbo’s Secret Stuff Vol. 1.',stops:[
  {name:'GRIZTRONICS / SPACE INVADERZ / MS. JACKSON',kind:'Track 1 · SoundCloud exclusive',description:'GRiZ & Subtronics (Cyclops Remix) × Joogornot × TIKI Edit.',x:68,y:26,w:39,h:9,url:'https://soundcloud.com/mumbobeatz'},
  {name:'YOU & ME × TURN ON THE LIGHTS',kind:'Track 2 · SoundCloud exclusive',description:'Flume (Westend & Local Singles Remix) × Fred again.. (Z A K Edit).',x:68,y:36,w:39,h:9,url:'https://soundcloud.com/mumbobeatz'},
  {name:'DON’T LET ME DOWN × COLD HEARTED',kind:'Track 3 · SoundCloud exclusive',description:'Chainsmokers (Spag Heddy Remix) × Seven Lions & Kill The Noise.',x:68,y:46,w:39,h:9,url:'https://soundcloud.com/mumbobeatz'},
  {name:'RENEGADE MASTA',kind:'Track 4 · SoundCloud exclusive',description:'Mumbo Flip · Released May 15, 2024.',x:68,y:56,w:39,h:9,url:'https://soundcloud.com/mumbobeatz'}
 ]}
};
