(()=>{
 const details=document.getElementById('gpsDetails'),selector=document.getElementById('worldSelector'),reelWorld=document.getElementById('reelWorld');
 const keys=['music','media','about','events','toys'];
 const labels={music:'Music Island',media:'Media Center',about:'Mumbo’s Moon',events:'Event Central',toys:'Mumbo’s Playground'};
 let selected=0,dragStart=null;const topWorld=name=>SUBWORLDS[name]?'music':keys.includes(name)?name:null;
 function showWorldInfo(key){details.innerHTML=`<p class="world-description">${WORLD_INFO[key]}</p>`}
 function render(key=keys[selected]){selected=Math.max(0,keys.indexOf(key));const next=labels[keys[selected]];if(reelWorld.textContent!==next){reelWorld.textContent=next;if(!matchMedia('(prefers-reduced-motion: reduce)').matches)reelWorld.animate?.([{transform:'translateY(14px) rotateX(-55deg)',opacity:.35},{transform:'translateY(0) rotateX(0)',opacity:1}],{duration:260,easing:'ease-out'})}selector.dataset.world=keys[selected];if(current==='hub'||current==='galaxy')showWorldInfo(keys[selected])}
 function rotate(step){selected=(selected+step+keys.length)%keys.length;render()}
 function enter(){const key=keys[selected];if(current!==key)travel(key,document.querySelector(`.island[data-go="${key}"]`)||selector)}
 document.getElementById('reelUp').addEventListener('click',()=>rotate(-1));document.getElementById('reelDown').addEventListener('click',()=>rotate(1));document.getElementById('reelEnter').addEventListener('click',enter);
 const wheel=selector.querySelector('.reel-window');wheel.style.touchAction='none';wheel.addEventListener('pointerdown',e=>{dragStart=e.clientY;wheel.setPointerCapture(e.pointerId)});wheel.addEventListener('pointerup',e=>{if(dragStart===null)return;const dy=e.clientY-dragStart;dragStart=null;if(Math.abs(dy)>18)rotate(dy>0?1:-1)});wheel.addEventListener('pointercancel',()=>dragStart=null);selector.addEventListener('wheel',e=>{e.preventDefault();e.stopPropagation();if(Math.abs(e.deltaY)>2)rotate(e.deltaY>0?1:-1)},{passive:false});selector.addEventListener('keydown',e=>{if(e.key==='ArrowUp'){e.preventDefault();rotate(-1)}if(e.key==='ArrowDown'){e.preventDefault();rotate(1)}if(e.key==='Enter'&&!e.target.closest('button')){e.preventDefault();enter()}});
 window.resetGps=()=>{if(SUBWORLDS[current]){details.innerHTML=`<p class="world-description">${SUBWORLDS[current].info}</p>`;return}const key=topWorld(current)||keys[selected];showWorldInfo(key)};
 window.showGpsStop=stop=>{details.innerHTML=`<h2>${stop.name}</h2><p>${stop.kind}</p><small>${stop.description||''}</small>${stop.url?link(stop.url,stop.label||'Open →','gps-link'):''}`};
 window.syncWorldSelector=name=>{const key=topWorld(name);if(key){selected=keys.indexOf(key);reelWorld.textContent=labels[key];selector.dataset.world=key}window.resetGps()};
 document.getElementById('gpsOpen').onclick=openDirectory;document.querySelectorAll('.island').forEach(island=>{const update=()=>{if(busy||current!=='hub')return;const key=island.dataset.go;if(!keys.includes(key))return;selected=keys.indexOf(key);render(key)};island.addEventListener('pointerenter',update);island.addEventListener('focus',update)});
 const knob=document.getElementById('volumeDial'),range=document.getElementById('volume');knob.setAttribute('role','slider');knob.setAttribute('tabindex','0');knob.setAttribute('aria-label','Volume');knob.setAttribute('aria-valuemin','0');knob.setAttribute('aria-valuemax','100');let drag=null;
 function change(value){range.value=Math.max(0,Math.min(100,Math.round(value)));range.dispatchEvent(new Event('input',{bubbles:true}));knob.setAttribute('aria-valuenow',range.value)}
 knob.addEventListener('pointerdown',e=>{e.preventDefault();drag={y:e.clientY,value:Number(range.value)};knob.setPointerCapture(e.pointerId)});knob.addEventListener('pointermove',e=>{if(drag)change(drag.value+(drag.y-e.clientY)*.7)});knob.addEventListener('pointerup',()=>drag=null);knob.addEventListener('pointercancel',()=>drag=null);knob.addEventListener('keydown',e=>{if(['ArrowUp','ArrowRight','ArrowDown','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();change(e.key==='Home'?0:e.key==='End'?100:Number(range.value)+(e.key==='ArrowUp'||e.key==='ArrowRight'?5:-5))}});range.addEventListener('input',()=>knob.setAttribute('aria-valuenow',range.value));knob.setAttribute('aria-valuenow',range.value);window.syncWorldSelector(current);
})();
