(()=>{
const flight=document.getElementById('flightView'),ground=document.getElementById('flightGround');
window.flyWorld=(world,reverse)=>{flight.hidden=false;ground.src=`assets/${CITIES[world].image}.webp`;flight.dataset.world=world;flight.querySelector('.fly-past.left').src=world==='toys'?'assets/construction-sign.webp':'assets/foreground-left.webp';flight.querySelector('.fly-past.right').src=world==='toys'?'assets/construction-sign.webp':'assets/foreground-right.webp';flight.classList.remove('inbound','outbound');void flight.offsetWidth;flight.classList.add(reverse?'outbound':'inbound')};
const stage=document.getElementById('cityStage');document.addEventListener('pointermove',e=>{if(paused||!CITIES[current]||e.pointerType==='touch')return;stage.style.setProperty('--view-x',((e.clientX/innerWidth-.5)*-9)+'px');stage.style.setProperty('--view-y',((e.clientY/innerHeight-.5)*-6)+'px');stage.style.setProperty('--view-angle',((e.clientX/innerWidth-.5)*.8)+'deg')});
const canvas=document.getElementById('cursorSmoke'),ctx=canvas.getContext('2d');let smoke=[],last=0,lastX=0,lastY=0;
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);
document.addEventListener('pointermove',e=>{if(paused||e.pointerType!=='mouse')return;const now=performance.now();if(now-last<16)return;const dx=e.clientX-lastX,dy=e.clientY-lastY,speed=Math.min(2.2,Math.hypot(dx,dy)/12);last=now;lastX=e.clientX;lastY=e.clientY;for(let i=0;i<2;i++)smoke.push({x:e.clientX+9+(Math.random()-.5)*7,y:e.clientY+23+(Math.random()-.5)*7,r:4+Math.random()*3,life:1,vx:-dx*.018+(Math.random()-.5)*.7,vy:-dy*.012-.3-Math.random()*.35,spin:(Math.random()-.5)*.08,depth:.65+Math.random()*.35,speed});if(smoke.length>72)smoke.splice(0,smoke.length-72)});
let prev=0;function draw(now){const dt=Math.min((now-prev)/16.7,3);prev=now;ctx.clearRect(0,0,canvas.width,canvas.height);if(paused){smoke=[]}else{smoke.forEach(p=>{p.life-=.018*dt;p.vx+=p.spin*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.r+=(p.depth*.24+p.speed*.05)*dt;const alpha=Math.max(0,p.life),edge=ctx.createRadialGradient(p.x-p.r*.22,p.y-p.r*.25,p.r*.06,p.x,p.y,p.r*1.35);edge.addColorStop(0,`rgba(238,248,255,${alpha*.62})`);edge.addColorStop(.28,`rgba(151,196,232,${alpha*.48})`);edge.addColorStop(.67,`rgba(69,91,137,${alpha*.34})`);edge.addColorStop(.9,`rgba(29,22,61,${alpha*.18})`);edge.addColorStop(1,'rgba(12,10,35,0)');ctx.save();ctx.shadowColor=`rgba(106,183,255,${alpha*.34})`;ctx.shadowBlur=8+p.r*.8;ctx.fillStyle=edge;ctx.beginPath();ctx.ellipse(p.x,p.y,p.r*1.15,p.r*.82,Math.sin(now*.001+p.spin)*.35,0,Math.PI*2);ctx.fill();ctx.restore()});smoke=smoke.filter(p=>p.life>0)}requestAnimationFrame(draw)}requestAnimationFrame(draw);
})();
