(()=>{
const flight=document.getElementById('flightView'),ground=document.getElementById('flightGround');
window.flyWorld=(world,reverse)=>{flight.hidden=false;ground.src=`assets/${CITIES[world].image}.webp`;flight.dataset.world=world;flight.querySelector('.fly-past.left').src=world==='toys'?'assets/construction-sign.webp':'assets/foreground-left.webp';flight.querySelector('.fly-past.right').src=world==='toys'?'assets/construction-sign.webp':'assets/foreground-right.webp';flight.classList.remove('inbound','outbound');void flight.offsetWidth;flight.classList.add(reverse?'outbound':'inbound')};
const stage=document.getElementById('cityStage');document.addEventListener('pointermove',e=>{if(paused||!CITIES[current]||e.pointerType==='touch')return;stage.style.setProperty('--view-x',((e.clientX/innerWidth-.5)*-9)+'px');stage.style.setProperty('--view-y',((e.clientY/innerHeight-.5)*-6)+'px');stage.style.setProperty('--view-angle',((e.clientX/innerWidth-.5)*.8)+'deg')});
const canvas=document.getElementById('cursorSmoke'),ctx=canvas.getContext('2d');let smoke=[],last=0;
function resize(){canvas.width=innerWidth;canvas.height=innerHeight}resize();addEventListener('resize',resize);
document.addEventListener('pointermove',e=>{if(paused||e.pointerType!=='mouse')return;const now=performance.now();if(now-last<20)return;last=now;smoke.push({x:e.clientX+12,y:e.clientY+20,r:3.2,life:1,vx:(Math.random()-.5)*.55});if(smoke.length>42)smoke.shift()});
let prev=0;function draw(now){const dt=Math.min((now-prev)/16.7,3);prev=now;ctx.clearRect(0,0,canvas.width,canvas.height);if(paused){smoke=[]}else{smoke.forEach(p=>{p.life-=.032*dt;p.y-=.35*dt;p.x+=p.vx*dt;p.r+=.22*dt;const glow=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.r);glow.addColorStop(0,`rgba(215,233,255,${Math.max(0,p.life)*.31})`);glow.addColorStop(1,'rgba(180,204,244,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fill()});smoke=smoke.filter(p=>p.life>0)}requestAnimationFrame(draw)}requestAnimationFrame(draw);
})();
